/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bibliotecagrupo3.Views;

import bibliotecaGrupo3.Controllers.Conexion;
import bibliotecagrupo3.Controllers.Helpers;
import bibliotecagrupo3.Controllers.LectorData;
import bibliotecagrupo3.Controllers.LibroData;
import bibliotecagrupo3.Controllers.MultaData;
import bibliotecagrupo3.Controllers.PrestamoData;
import bibliotecagrupo3.Models.Lector;
import bibliotecagrupo3.Models.Libro;
import bibliotecagrupo3.Models.Prestamo;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rodrigo
 */
public class PrestamosByLector extends javax.swing.JInternalFrame {
    private DefaultTableModel tableModel;
    private PrestamoData pData;
    private LectorData lData;
    private LibroData libroData;
    private Lector lector;
    
    
    public PrestamosByLector(Conexion conexion) throws SQLException {
        initComponents();
        
        pData = new PrestamoData(conexion);
        lData = new LectorData(conexion);
        libroData = new LibroData(conexion);
        tableModel = new DefaultTableModel();
        buildTableHeader();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTFDni = new javax.swing.JTextField();
        jBBuscar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePrestamos = new javax.swing.JTable();
        jBSalir = new javax.swing.JButton();
        jBLimpiar = new javax.swing.JButton();

        setTitle("Prestamos por Lector");

        jLabel1.setText("DNI:");

        jBBuscar.setText("BUSCAR");
        jBBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBuscarActionPerformed(evt);
            }
        });

        jTablePrestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTablePrestamos.setRowHeight(20);
        jScrollPane1.setViewportView(jTablePrestamos);

        jBSalir.setText("SALIR");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        jBLimpiar.setText("LIMPIAR");
        jBLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBLimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(jTFDni)
                        .addGap(18, 18, 18)
                        .addComponent(jBBuscar)
                        .addGap(22, 22, 22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jBLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(jBSalir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBBuscar))
                    .addComponent(jLabel1))
                .addGap(16, 16, 16)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBSalir)
                    .addComponent(jBLimpiar))
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBuscarActionPerformed
        int dniLector = Helpers.parseStringToInt(jTFDni.getText(), "Dni requerido para poder buscar", "Un DNI solo debe contener numeros.");
        
        lector = lData.buscarLector(dniLector);
        
        if(lector == null) return;
        
        ArrayList<Prestamo> prestamos = pData.getByLector(lector);
        
        clearTable();
        
        for(Prestamo prestamo:prestamos){
            Libro libro = prestamo.getEjemplar().getLibro();
            
            String generoMulta = "No";
            
            if(prestamo.getMulta() != null){
                generoMulta = "Si";
            }
            
            tableModel.addRow(new Object[]{libro.getNombre(), prestamo.getFecha(),prestamo.getFecha_devolucion(),generoMulta});
        }
    }//GEN-LAST:event_jBBuscarActionPerformed

    private void jBLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBLimpiarActionPerformed
        clearTable();
        jTFDni.setText("");
    }//GEN-LAST:event_jBLimpiarActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jBSalirActionPerformed

    private void clearTable(){ 
       int rowCount = tableModel.getRowCount()-1;
       
       for(int i = rowCount; i >= 0; i--){
           tableModel.removeRow(i);
       }
    }
    
    private void buildTableHeader(){
        ArrayList <Object> columnas = new ArrayList<>();
        
        columnas.add("Libro");
        columnas.add("Fecha de prestamo");
        columnas.add("Fecha de devolucion");
        columnas.add("Genero Multa");
        
        for(Object it:columnas){
            tableModel.addColumn(it);
        }
        
        jTablePrestamos.setModel(tableModel);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBuscar;
    private javax.swing.JButton jBLimpiar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTFDni;
    private javax.swing.JTable jTablePrestamos;
    // End of variables declaration//GEN-END:variables
}
